'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, AudioLines, Check, CircleHelp, LockKeyhole, RotateCcw, Trash2, VolumeX, Wind } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Progress } from '@/components/ui/progress';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import type { createGame } from '@/lib/game-engine';
import { registerGameTools } from '@/lib/webmcp';
export default function Home(){
  const host=useRef<HTMLDivElement>(null),engine=useRef<ReturnType<typeof createGame>|null>(null);
  const [level,setLevel]=useState(1),[score,setScore]=useState(0),[shots,setShots]=useState(0),[hits,setHits]=useState(0),[power,setPower]=useState(47),[aim,setAim]=useState(0),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[help,setHelp]=useState(false),[transition,setTransition]=useState(false),[muted,setMuted]=useState(false),[restart,setRestart]=useState(0),[error,setError]=useState(''),[message,setMessage]=useState('Your outie can wait. Take the shot.');
  const live=useRef({level,score,aim,power,busy,ready,transition,help});live.current={level,score,aim,power,busy,ready,transition,help};
  const scoreRef=useRef(0),mutedRef=useRef(false),audio=useRef<AudioContext|null>(null);
  function sound(success:boolean){if(mutedRef.current)return;try{audio.current??=new AudioContext();void audio.current.resume();const ctx=audio.current;for(let i=0;i<(success?3:1);i++){const osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.type='sine';osc.frequency.setValueAtTime(success?[523,659,784][i]:190,ctx.currentTime+i*.085);gain.gain.setValueAtTime(.055,ctx.currentTime+i*.085);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+i*.085+.18);osc.start(ctx.currentTime+i*.085);osc.stop(ctx.currentTime+i*.085+.2);}}catch{}}
  useEffect(()=>{let cancelled=false;setReady(false);setError('');setBusy(false);setPower(47);setAim(0);import('@/lib/game-engine').then(({createGame})=>{if(cancelled||!host.current)return;engine.current=createGame(host.current,level,{onScore(){scoreRef.current+=10;setScore(scoreRef.current);setHits(v=>v+1);setMessage('+10 · Beautifully disposed.');sound(true);if(scoreRef.current===100)setTransition(true);},onShot(){setBusy(true);setShots(v=>v+1);setMessage('Paper in flight…');sound(false);},onReady(){setBusy(false);},onMessage:setMessage,onAim(a,p){setAim(a);setPower(p);}});setReady(true);}).catch(()=>setError('The 3D room could not load. Enable WebGL in your browser, then reload.'));return()=>{cancelled=true;engine.current?.destroy();engine.current=null;};},[level,restart]);
  useEffect(()=>{engine.current?.setPaused(help||transition);},[help,transition]);
  useEffect(()=>{function key(e:KeyboardEvent){if(help||transition||!engine.current||e.target instanceof HTMLInputElement||e.target instanceof HTMLButtonElement||(e.target as HTMLElement)?.getAttribute('role')==='slider')return;const s=engine.current.getState();if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key===' ')engine.current.shoot();if(e.key==='ArrowLeft')engine.current.setAim(s.aim-.012,s.power);if(e.key==='ArrowRight')engine.current.setAim(s.aim+.012,s.power);if(e.key==='ArrowUp')engine.current.setAim(s.aim,s.power+1);if(e.key==='ArrowDown')engine.current.setAim(s.aim,s.power-1);}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[help,transition]);
  useEffect(()=>registerGameTools(()=>({...live.current,...engine.current?.getState(),score:scoreRef.current}), (a,p)=>{if(!engine.current||live.current.help||live.current.transition)return false;engine.current.setAim(a,p);return engine.current.shoot();},()=>{setTransition(false);setLevel(2);setMessage('You’re off the clock. Make yourself at home.');}),[]);
  function reset(){scoreRef.current=0;setScore(0);setShots(0);setHits(0);setLevel(1);setTransition(false);setRestart(v=>v+1);setMessage('A fresh start. Make it count.');}
  function next(){setTransition(false);setLevel(2);setMessage('You’re off the clock. Make yourself at home.');}
  return <main className={'game-shell '+(level===2?'beach':'')}>
    <header className="topbar"><a className="brand" href="/" aria-label="Trashketball home"><span className="brand-mark"><Trash2 size={21}/></span><span>trashketball<span className="brand-period">.</span></span></a><div className="chapter-nav"><span className={level===1?'chapter active':'chapter done'}><span className="chapter-number">{level===2?<Check size={12}/>: '01'}</span>The office</span><span className="chapter-line"/><span className={level===2?'chapter active':'chapter'}><span className="chapter-number">{level===1?<LockKeyhole size={11}/>: '02'}</span>The escape</span></div><div className="top-actions"><button aria-label={muted?'Enable sound':'Mute sound'} title={muted?'Enable sound':'Mute sound'} onClick={()=>{setMuted(!muted);mutedRef.current=!muted;}}>{muted?<VolumeX size={18}/>:<AudioLines size={18}/>}</button><button aria-label="How to play" title="How to play" onClick={()=>setHelp(true)}><CircleHelp size={19}/></button><button className="restart" title="Restart game" onClick={reset}><RotateCcw size={16}/><span>Restart</span></button></div></header>
    <section className="play-area" aria-label={level===1?'3D office trashketball court':'3D beach house trashketball court'}>
      <div className="scene" ref={host}/><div className="scene-vignette"/>
      {!ready&&<div className="loading-room" role="status">{error||'Opening the room…'}</div>}
      <div className="scene-top"><div className="room-tag"><span className="live-dot"/> {level===1?'LUMON INDUSTRIES':'OUT OF OFFICE'}<span className="tag-divider"/>{level===1?'SEVERED FLOOR':'COASTAL RESIDENCE'}</div><div className="score-card"><div className="score-heading">{level===1?'YOUR SCORE':'TOTAL SCORE'}<span>+10 per basket</span></div><div className="score-value">{String(score).padStart(2,'0')}<span>pts</span></div><Progress aria-label="Progress to beach house" value={Math.min(score,100)}/><div className="score-caption">{level===1?<><LockKeyhole size={12}/>{100-score} points to your escape</>:<><Check size={13}/> Beach house unlocked</>}</div></div></div>
      <div className="shot-feedback" role="status" aria-live="polite" key={message}>{message.startsWith('+10')?<span className="made-shot">{message}</span>:null}</div>
      <div className="scene-bottom"><div className="room-title"><div className="eyebrow">LEVEL {String(level).padStart(2,'0')}<span/>{level===1?'PLEASE ENJOY EACH THROW EQUALLY.':'YOUR WELL-EARNED CHANGE OF SCENERY.'}</div><h1>{level===1?'Severance pay.':'Paradise, found.'}</h1><p>{level===1?'Another day. Another paper trail.':'A little less work. A lot more ocean.'}</p></div><div className="conditions"><span><Wind size={15}/> No wind</span><span className="condition-dot"/><span>{level===1?'7.2':'8.0'} m to basket</span></div></div>
      <div className="aim-hint"><span className="hint-line"/>PAPER BALL<span className="hint-line"/></div>
    </section>
    <section className="control-deck" aria-label="Throw controls"><div className="play-instruction"><span className="gesture-icon"><ArrowDown size={22}/></span><div><h2>Small ball. Big escape.</h2><p>Drag down for power, sideways to aim. Release to throw.</p></div></div><div className="aim-control"><div className="control-label"><span>AIM</span><span>{aim<-.005?'LEFT':aim>.005?'RIGHT':'CENTER'}</span></div><Slider aria-label="Aim left or right" min={-48} max={48} step={.5} value={[aim*100]} disabled={!ready||busy} onValueChange={v=>engine.current?.setAim((Array.isArray(v)?v[0]:v)/100,power)}/></div><div className="power-control"><div className="control-label"><span>POWER</span><span>{Math.round(power)}<small>%</small></span></div><Slider aria-label="Throw power" min={0} max={100} step={1} value={[power]} disabled={!ready||busy} onValueChange={v=>engine.current?.setAim(aim,Array.isArray(v)?v[0]:v)}/></div><button className="throw-button" disabled={!ready||busy||transition} onClick={()=>engine.current?.shoot()}>{busy?'In flight…':'Take the shot'}<ArrowUpRight size={19}/></button></section>
    <footer><span><i/> {busy?'SHOT IN PROGRESS':ready?'READY WHEN YOU ARE':'PREPARING YOUR DESK'}</span><span className="keyboard-help"><kbd>←</kbd><kbd>→</kbd> aim <span>·</span><kbd>↑</kbd><kbd>↓</kbd> power <span>·</span><kbd>space</kbd> throw</span><span>{hits} baskets<span className="footer-divider">/</span>{shots} throws</span></footer>
    <Dialog open={help} onOpenChange={setHelp}><DialogContent className="game-dialog"><div className="dialog-icon"><Trash2/></div><DialogTitle>Make a little waste of time.</DialogTitle><DialogDescription>Land crumpled paper in the basket for 10 points. Reach 100 points to leave the office for your beachside escape.</DialogDescription><div className="help-steps"><p><b>01 / Line it up</b>Use the aim slider or left and right arrow keys.</p><p><b>02 / Find your power</b>Follow the dotted arc. Adjust power with the slider or up and down arrows.</p><p><b>03 / Let it fly</b>Press space or Take the shot. You can also drag in the room and release to throw.</p></div><button className="throw-button" onClick={()=>setHelp(false)}>Back to the room<ArrowRight size={18}/></button></DialogContent></Dialog>
    <Dialog open={transition} onOpenChange={v=>{if(!v)next();}}><DialogContent className="game-dialog escape-dialog" showCloseButton={false}><span className="eyebrow">LEVEL 01 COMPLETE</span><div className="escape-symbol">↗</div><DialogTitle>Your outie has plans.</DialogTitle><DialogDescription>100 points. Ten excellent decisions.<br/>Your beach house is ready. Leave the fluorescent lights behind.</DialogDescription><button className="throw-button" onClick={next}>Clock out. Check in.<ArrowUpRight size={20}/></button></DialogContent></Dialog>
  </main>;
}
