import * as THREE from 'three';
import { buildOffice, buildBeach, makePaper } from './rooms';
import { BALL_RADIUS, BINS, ORIGIN, launchVelocity, integrate, entersBin, rimCollision } from './physics';
export type GameEvents = { onScore:()=>void; onShot:()=>void; onReady:()=>void; onMessage:(text:string)=>void; onAim:(aim:number,power:number)=>void; };
export function createGame(container:HTMLElement,level:number,events:GameEvents) {
  const scene=new THREE.Scene();const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;container.appendChild(renderer.domElement);
  const camera=new THREE.PerspectiveCamera(56,1,.05,150);camera.position.set(0,1.75,4.2);camera.lookAt(0,1.2,-6);level===1?buildOffice(scene):buildBeach(scene);
  let aim=0,power=47,busy=false,paused=false,scored=false,age=0,accumulator=0;const ball=makePaper();scene.add(ball);ball.position.copy(ORIGIN);ball.scale.setScalar(1.6);
  let position={...ORIGIN},velocity=launchVelocity(aim,power);const settled:THREE.Mesh[]=[];
  const dots=new THREE.Group();scene.add(dots);const dotGeo=new THREE.SphereGeometry(.026,8,6);const dotMat=new THREE.MeshBasicMaterial({color:level===1?'#f2e6b2':'#ffffff',transparent:true,opacity:.85,depthTest:true});for(let i=0;i<48;i++)dots.add(new THREE.Mesh(dotGeo,dotMat));
  const marker=new THREE.Mesh(new THREE.RingGeometry(.12,.15,32),new THREE.MeshBasicMaterial({color:'#e9d58e',side:THREE.DoubleSide,transparent:true,opacity:.75}));marker.rotation.x=-Math.PI/2;scene.add(marker);
  const shadow=new THREE.Mesh(new THREE.CircleGeometry(.16,32),new THREE.MeshBasicMaterial({color:'#182a21',transparent:true,opacity:.2,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.008;scene.add(shadow);
  function trajectory(){const p={...ORIGIN},v=launchVelocity(aim,power);let ended=false;for(let i=0;i<48;i++){for(let j=0;j<12;j++)integrate(p,v,1/240);const dot=dots.children[i];dot.position.set(p.x,p.y,p.z);dot.visible=!ended&&p.y>0;dot.scale.setScalar(1+i*.012);if(p.y<.02)ended=true;}const vv=launchVelocity(aim,power);const tf=(vv.y+Math.sqrt(vv.y*vv.y+2*9.81*ORIGIN.y))/9.81;marker.position.set(ORIGIN.x+vv.x*tf,.012,ORIGIN.z+vv.z*tf);}
  function setAim(a:number,p:number){if(busy||paused)return;aim=Math.max(-.48,Math.min(.48,a));power=Math.max(0,Math.min(100,p));trajectory();events.onAim(aim,power);}
  function shoot(){if(busy||paused)return false;busy=true;scored=false;age=0;accumulator=0;position={...ORIGIN};velocity=launchVelocity(aim,power);ball.position.copy(position);ball.scale.setScalar(1);dots.visible=false;marker.visible=false;events.onShot();return true;}
  function ready(){busy=false;const old=makePaper();old.position.copy(ball.position);old.rotation.copy(ball.rotation);scene.add(old);settled.push(old);if(settled.length>20){const removed=settled.shift()!;scene.remove(removed);removed.geometry.dispose();(removed.material as THREE.Material).dispose();}ball.position.copy(ORIGIN);ball.scale.setScalar(1.6);dots.visible=true;marker.visible=true;events.onReady();if(!scored)events.onMessage('Almost. Adjust your aim and try again.');}
  function step(dt:number){const previous={...position};integrate(position,velocity,dt);age+=dt;const b=BINS[level-1];rimCollision(position,velocity,b);if(!scored&&velocity.y<0&&entersBin(previous,position,b)){scored=true;events.onScore();}
    const dx=position.x-b.x,dz=position.z-b.z,dist=Math.hypot(dx,dz);if(position.y<b.height-.07&&position.y>BALL_RADIUS&&dist>.0001){const radius=b.bottomRadius+(b.radius-b.bottomRadius)*position.y/b.height;const inside=dist<radius;if(Math.abs(dist-radius)<BALL_RADIUS){const n=inside?-1:1;position.x=b.x+dx/dist*(radius+n*BALL_RADIUS);position.z=b.z+dz/dist*(radius+n*BALL_RADIUS);const dot=(velocity.x*dx+velocity.z*dz)/dist*n;if(dot<0){velocity.x-=1.35*dot*dx/dist*n;velocity.z-=1.35*dot*dz/dist*n;}}}
    const floor=scored?.14:BALL_RADIUS;if(position.y<floor){position.y=floor;if(velocity.y<0)velocity.y*=-.28;velocity.x*=.79;velocity.z*=.79;}
    if(Math.abs(position.x)>11.6){position.x=Math.sign(position.x)*11.6;velocity.x*=-.3;}if(position.z<-13.6){position.z=-13.6;velocity.z*=-.3;}
    ball.position.copy(position);ball.rotation.x+=dt*velocity.z*2;ball.rotation.z-=dt*velocity.x*2;shadow.position.set(position.x,.01,position.z);shadow.scale.setScalar(1+position.y*.4);(shadow.material as THREE.MeshBasicMaterial).opacity=.18/(1+position.y*.5);
    if(age>4||(position.y<=floor+.01&&Math.abs(velocity.y)<.4&&age>1.2))ready();}
  let start:{x:number;y:number;a:number;p:number}|null=null;
  function down(e:PointerEvent){if(busy||paused)return;renderer.domElement.setPointerCapture(e.pointerId);start={x:e.clientX,y:e.clientY,a:aim,p:power};events.onMessage('Pull down for power. Drag sideways to aim.');}
  function move(e:PointerEvent){if(!start)return;setAim(start.a+(e.clientX-start.x)*.0018,start.p+(e.clientY-start.y)*.23);}
  function up(){if(start){start=null;shoot();}}
  function cancel(){start=null;}
  const canvas=renderer.domElement;canvas.style.touchAction='none';canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',cancel);
  function resize(){const {width,height}=container.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/Math.max(1,height);camera.fov=width<650?68:56;camera.updateProjectionMatrix();}const observer=new ResizeObserver(resize);observer.observe(container);resize();trajectory();
  let frame=0,last=performance.now();function animate(now:number){const delta=Math.min((now-last)/1000,.05);last=now;if(!paused){if(busy){accumulator+=delta;while(accumulator>=1/240&&busy){step(1/240);accumulator-=1/240;}}else {ball.position.y=ORIGIN.y+Math.sin(now*.002)*.015;ball.rotation.y+=delta*.12;}}renderer.render(scene,camera);frame=requestAnimationFrame(animate);}frame=requestAnimationFrame(animate);
  return {setAim,shoot,setPaused(value:boolean){paused=value;},getState(){return{aim,power,busy,level};},destroy(){cancelAnimationFrame(frame);observer.disconnect();canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',cancel);const geos=new Set<THREE.BufferGeometry>(),mats=new Set<THREE.Material>(),textures=new Set<THREE.Texture>();scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line){geos.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){mats.add(m);for(const v of Object.values(m))if(v instanceof THREE.Texture)textures.add(v);}}});geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.dispose();canvas.remove();}};
}
